stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template
  tags: [ build ]
  script:
    - pip install pytest
    - pip install pytest-html
    - pip install selenium
    - pytest --html=reports/report.html test_login.py
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - reports/**
