stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: ppodgorsek/robot-framework

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template   
  tags: [ build ]
  script: robot --outputdir results --variable BROWSER:chrome --variable ENVIRONMENT:DEV features-frontend/flights.feature.robot  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'         
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
    - if: '$CI_PIPELINE_SOURCE == "web"'          
