stages:
  - build
  - run

variables:
  ARTIFACT_REPORT_PATH: "${CI_PROJECT_DIR}/reports"

build_image:
  stage: build
  variables:
    DOCKER_IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  script:
    - docker build -t ${DOCKER_IMAGE_TAG} .
  after_script:
    - docker push ${DOCKER_IMAGE_TAG}
    - docker logout

robot_tests:
  stage: run
  variables:
    DOCKER_IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  image: ${DOCKER_IMAGE_TAG}
  script:
    - robot-test.sh
  artifacts:
    paths:
      - $ARTIFACT_REPORT_PATH
    when: always