stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template   
  tags: [ build ]
  rules:
    - when: always
  script:
    - if ($ENVIRONMENT -eq "DEV") {
        Write-Host "Running in DEV environment"
         }
    - if ($FEATURE -eq "All") {
        Write-Host "Running all features"
      }
