stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template
  tags: [ build ]   
  script:
    - echo "Building Booking ..."
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - results/output.xml
      - results/log.html
      - results/report.html
