stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template
  tags: [ build ]
  script:
    - pip install -r requirements.txt
    - robot features-frontend/__init__.robot --outputdir results --report results/report.html --log results/log.html
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - reports/**
