stages:
  - sanity-frontend

image: ppodgorsek/robot-framework:latest

variables:
  ROBOT_TESTS_DIR: "/results"

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  script:
    - echo "Building Booking ..."
    - robot -d results /results
  extends: .sanity-fe-template
  tags: [ build ]  
  


