stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

image: apps.booking.com

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template
  tags: [ build ]
    rules:
    - if: '$TRIGGER_SANITY_FE == "true"'           
    - if: '$CI_PIPELINE_SOURCE == "push"'         
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
    - if: '$CI_PIPELINE_SOURCE == "web"'          
  script:
    - echo "Building Booking ..."
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - reports/**
