stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking:latest

run-sanity-checks-fe:
  stage: sanity-frontend
  script:
  - bash -c "python3 --version || echo 'Python3 ÇALIŞMIYOR!'"
  - bash -c "python3 -m pip --version || echo 'Pip ÇALIŞMIYOR!'"
  - bash -c "python3 -m robot --version || echo 'Robot Framework YOK!'"
  artifacts:
    when: always
    paths:
      - results/report.html
      - results/log.html
    expire_in: 1 week
  allow_failure: true
