image: registry.gitlab.com/balamirr/testinium-booking:latest

stages:
  - test

test:
  script:
    - $env:PATH="$env:PATH;C:\Users\$env:USERNAME\AppData\Local\Programs\Python\Python313\Scripts;C:\Users\$env:USERNAME\AppData\Local\Programs\Python\Python313\"
    - echo $env:PATH
    - python3 --version
    - robot --version
    - echo "python3 --version"
