stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking:latest

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template
  tags: [build]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - echo "Running sanity frontend for the ${ENVIRONMENT} environment..."
    - echo "Browser- $BROWSER"
    - pip install --no-cache-dir -r requirements.txt
    - |
      if [ "$ENVIRONMENT" = "DEV" ]; then
        if [ "$FEATURE" = "All" ]; then
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable RESOLUTION:${RESOLUTION} --variable ENVIRONMENT:${ENVIRONMENT} --include ${ENVIRONMENT} features-frontend
        else
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable RESOLUTION:${RESOLUTION} --variable ENVIRONMENT:${ENVIRONMENT} --include ${ENVIRONMENT}AND${FEATURE} features-frontend
        fi
      fi
  artifacts:
    when: always
    paths:
      - results
    expire_in: 1 week
  allow_failure: true