stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking:latest

run-sanity-checks-fe:
  stage: sanity-frontend
  script:
    - bash -c "python3 -m robot --version"
    - bash -c "robot --version"
    - bash -c "pip install -r requirements.txt"
    - bash -c "which robot || echo 'Robot Framework bulunamadı'"
    - bash -c "mkdir -p results && ls -la results"
    - export PATH="/usr/bin:$PATH"
    - bash -c "python3 -m robot --outputdir results --variable BROWSER:chrome --variable ENVIRONMENT:DEV --variable RESOLUTION:1920x1080 features-frontend/*.robot"
  artifacts:
    when: always
    paths:
      - results/report.html
      - results/log.html
    expire_in: 1 week
  allow_failure: true
