stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template
  tags: [ build ]
  script:
    - $env:PATH = "C:\Users\furka\AppData\Local\Programs\Python\Python313\Scripts\;" + $env:PATH
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install selenium
    - robot features-frontend/__init__.robot --outputdir reports --report reports/report.html --log reports/log.html
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - reports/**
