default:
  before_script:
    - cd /C:/Testinium-Booking-Gitlab/Testinium-Booking
stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking:latest

run-sanity-checks-fe:
  stage: sanity-frontend
  script:
    - echo "Giriş yapıldı, ortam hazırlanıyor"
    - pip install -r requirements.txt
    - pabot --verbose -d results --variable BROWSER=$BROWSER --variable RESOLUTION=$RESOLUTION --variable ENVIRONMENT=$ENVIRONMENT --include $ENVIRONMENT features-frontend || echo "Testler çalıştırılamadı!"
  artifacts:
    when: always
    paths:
      - results
    expire_in: 1 week
  allow_failure: true
