stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking:latest

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template   
  tags: [ build ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'         
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
    - if: '$CI_PIPELINE_SOURCE == "web"'          
