stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  image: python:3.10
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
  - python --version
  - pip --version
  - pip install pytest
  - pytest --version
  - echo "Doing complex stuff"
  extends: .sanity-fe-template
  tags: [ build ]  

run tests:
  stage: sanity-frontend
  image: registry.gitlab.com/balamirr/testinium-booking
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - python --version
    - pip --version
    - pytest --version
    - echo "Doing complex stuff"

build image:
  stage: build
  image: docker
  services:
    - docker:dind
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t docker build -t registry.gitlab.com/balamirr/testinium-booking .
    - docker push docker push registry.gitlab.com/balamirr/testinium-booking

