stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

run-sanity-checks-fe:
  stage: sanity-frontend
  image: $IMAGE_TAG
  script:
    - bash
    - apt-get update && apt-get install -y curl dnsutils iputils-ping
    - echo "Running sanity frontend for the ${ENVIRONMENT} environment..."
    - echo "Browser:" $BROWSER
    - |
      if [ "$ENVIRONMENT" = "DEV" ]; then
        echo "Running DEV tests..."
        if [ "$FEATURE" = "All" ]; then
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable ENVIRONMENT:${ENVIRONMENT} features-frontend
        else
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable ENVIRONMENT:${ENVIRONMENT}  --include ${ENVIRONMENT}AND${FEATURE} features-frontend
        fi
      fi
  artifacts:
    when: always
    paths:
      - results
    expire_in: 1 week
  allow_failure: true

