stages:
  - build
  - test

# Build stage - Docker imajı oluşturulacak
build:
  stage: build
  image: python:3.9-slim  # Python 3.9 imajı kullanılacak
  script:
    - echo "Building the application..."
    - pip install --upgrade pip  # Pip'i güncelle
    - pip install -r requirements.txt  # Gereksinimlerinizi yükleyin
    - echo "Build completed"

# Test stage - Testler çalıştırılacak
test:
  stage: test
  image: python:3.9-slim  # Python 3.9 imajı kullanılacak
  script:
    - echo "Running tests..."
    - pytest tests  # Testler pytest ile çalıştırılacak
    - echo "Tests completed"
  artifacts:
    paths:
      - reports/  # Test raporlarını kaydetmek için kullanılan yol

# Cleanup stage - Gereksiz dosyaları temizle
cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up..."
    - rm -rf build/
    - echo "Cleanup completed"
