before_script:
  - pip install --no-cache-dir -r requirements.txt


stages:
  - test

test:
  stage: test
  script:
    - echo "Running tests with ${BROWSER} on ${ENVIRONMENT} environment"
    - pip install --no-cache-dir -r requirements.txt
    - |
      if [ "$ENVIRONMENT" = "DEV" ]; then
        if [ "$FEATURE" = "All" ]; then
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable ENVIRONMENT:${ENVIRONMENT} features-frontend
        else
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable ENVIRONMENT:${ENVIRONMENT} --include ${FEATURE} features-frontend
        fi
      fi
  artifacts:
    paths:
      - results
    expire_in: 1 week
  allow_failure: true

