stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template   
  tags: [ build ]