stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking:latest

run-sanity-checks-fe:
  stage: sanity-frontend
  script:
    - python -m robot --version
    - robot --version
    - pip install -r requirements.txt
    - pabot --verbose -d results --variable BROWSER=$BROWSER --variable RESOLUTION=$RESOLUTION --variable ENVIRONMENT=$ENVIRONMENT --include $ENVIRONMENT features-frontend"
  artifacts:
    when: always
    paths:
      - results/report.html
      - results/log.html
    expire_in: 1 week
  allow_failure: true
