stages:
  - sanity-frontend

include:
  - local: 'templates/qa-variables.yml' 
  - local: 'templates/sanity-checks-fe.yml'

image: registry.gitlab.com/balamirr/testinium-booking:latest

run-sanity-checks-fe:
  stage: sanity-frontend
  extends: .sanity-fe-template   
  tags: [ build ]
  script: "curl -X POST --fail -F token=glptt-47e1eb1bbbaefecf7b5031edd2bcb9cee08f7d70 -F ref=main https://gitlab.com/api/v4/projects/67711988/trigger/pipeline"  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'         
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' 
    - if: '$CI_PIPELINE_SOURCE == "web"'          
