image: registry.gitlab.com/balamirr/testinium-booking:latest

stages:
  - build
  - test

# Build stage - Docker imajı oluşturulacak
build:
  stage: build
  services:
    - docker:dind  # Docker in Docker kullanıyoruz
  script:
    - echo "Building Docker image..."
    # Docker imajı oluşturulacak
    - docker build -t my-python-app .  # Dockerfile bulunduğu dizin
    - docker run -v $PWD:/app my-python-app bash -c "pip install -r /app/requirements.txt"  # Gereksinimlerin yüklenmesi
    - echo "Build completed"

# Test stage - Testler çalıştırılacak
test:
  stage: test
  script:
    - echo "Running tests..."
    - pytest /app/tests  # Testlerin çalıştırılması
    - echo "Tests completed"
  artifacts:
    paths:
      - reports/  # Test raporlarını kaydetmek için kullanılan yol
