stages:
  - sanity-frontend

image: ppodgorsek/robot-framework:latest


include:
  - local: 'templates/qa-variables.yml'
  - local: 'templates/sanity-checks-fe.yml'

run-sanity-checks-fe:
  stage: sanity-frontend
  image: python:3
  script:
  - python --version
  - pip --version
  - pip install pytest
  - pytest --version
  - echo "Doing complex stuff"
  extends: .sanity-fe-template
  tags: [ build ]  
  
build image: 
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE

