stages:
  - build
  - test

variables:
  ENVIRONMENT: "DEV"
  FEATURE: "All"
  BROWSER: "chrome"

# Docker image'i kullanarak testleri çalıştıracak job
test:
  image: registry.gitlab.com/balamirr/testinium-booking:latest  # Docker imajınız
  stage: test
  script:
    - echo "Running tests on ${ENVIRONMENT} environment using ${BROWSER} browser..."
    - echo "Test feature:" ${FEATURE}
    - pip install --no-cache-dir -r requirements.txt
    - Xvfb :99 -ac -screen 0 1920x1080x24 & export DISPLAY=:99
    - |
      if [ "$ENVIRONMENT" = "DEV" ]; then
        if [ "$FEATURE" = "All" ]; then
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable ENVIRONMENT:${ENVIRONMENT} features-frontend
        else
          pabot --verbose -d results --variable BROWSER:${BROWSER} --variable ENVIRONMENT:${ENVIRONMENT} --include ${ENVIRONMENT}AND${FEATURE} features-frontend
        fi
      fi
  artifacts:
    when: always
    paths:
      - results
    expire_in: 1 week
  allow_failure: true
