NAV_MENU="css=.Header_bar"
APP_LOGO="css=span[data-testid='header-logo']"
LANGUAGE_PREF_DRAWER="css=.f419a93f12:nth-child(2) .e3fa9175ee"
LANGUAGE_ENG="css=.abced745f1"
DESTINATION_FIELD="//input[contains(@aria-label,'Where are you going?')]"
DESTINATION_LISTBOX="//div[@role='listbox']//ul//li"
DESTINATION_CITIES="//ul/li//div[contains(@class, 'a3332d346a')]"
CLEAR_BTN="css=.a83ed08757 > .fcd9eec8fb:nth-child(1) > svg"
DATE_PICKER="//button[@data-testid='date-display-field-start']"
SELECTED_DATE="//span[contains(@tabindex,'0')]"
ACCEPT_COOKIES="#onetrust-accept-btn-handler"
# DESTINATION_CITIES="//div[@data-testid='autocomplete-result']//div[contains(@class, 'a3332d346a')]"
