NAV_MENU="css=.Header_bar"
APP_LOGO="css=span[data-testid='header-logo']"
DESTINATION_FIELD="//input[contains(@aria-label,'Où allez-vous ?')]"
DESTINATION_LISTBOX="//div[@role='listbox']//ul//li"
DESTINATION_CITIES="//ul/li//div[contains(@class, 'a3332d346a')]"
CLEAR_BTN="css=.a83ed08757 > .fcd9eec8fb:nth-child(1) > svg"
DATE_PICKER="//button[@data-testid='date-display-field-start']"
# DESTINATION_CITIES="//div[@data-testid='autocomplete-result']//div[contains(@class, 'a3332d346a')]"